<?php

namespace AppBundle\Repository;

/**
 * admin_usersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class admin_usersRepository extends \Doctrine\ORM\EntityRepository
{
}
