<?php

namespace AppBundle\Repository;

/**
 * adminusers_roleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class adminusers_roleRepository extends \Doctrine\ORM\EntityRepository
{
}
