<?php

namespace AppBundle\Repository;

/**
 * app_usersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class app_usersRepository extends \Doctrine\ORM\EntityRepository
{
}
