<?php

namespace AppBundle\Repository;

/**
 * birthday_job_logRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class birthday_job_logRepository extends \Doctrine\ORM\EntityRepository
{
}
