<?php

namespace AppBundle\Repository;

/**
 * birthday_notification_confirmRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class birthday_notification_confirmRepository extends \Doctrine\ORM\EntityRepository
{
}
