<?php

namespace AppBundle\Repository;

/**
 * doctorsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class doctorsRepository extends \Doctrine\ORM\EntityRepository
{
}
