<?php

namespace AppBundle\Repository;

/**
 * push_tokensRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class push_tokensRepository extends \Doctrine\ORM\EntityRepository
{
}
