<?php

namespace AppBundle\Repository;

/**
 * sms_booking_confimRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class sms_booking_confimRepository extends \Doctrine\ORM\EntityRepository
{
}
