<?php

namespace AppBundle\Repository;

/**
 * storiesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class storiesRepository extends \Doctrine\ORM\EntityRepository
{
}
