<?php

namespace AppBundle\Repository;

/**
 * termsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class termsRepository extends \Doctrine\ORM\EntityRepository
{
}
